version: "3"

services:
  app:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    volumes:
      - ./www/html/:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
    restart: always
  db:
    image: mysql:5.7
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    command: --innodb-use-native-aio=0
    restart: always
